[package]
name = "zero"
edition = "2024"
version = "3.0.0"
license = "MIT License"
authors = ["Steven Ortiz"]

[lib]
doc = false

[[bin]]
name = "zero"
doc = false

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
