[package]
name = "zero"
edition = "2021"
version = "2.0.0"
license = "MIT License"
authors = ["Steven Ortiz"]

[lib]
doc = false

[[bin]]
name = "zero"
doc = false

[dependencies]
structopt = { version = "0.3.26", default-features = false }
